---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_PASSWORD
          value: root
        - name: WORDPRESS_DB_HOST
          value: mysql.backend.svc
        ports:
        - containerPort: 80

